import type { Config, Port } from "./types.js";

export default {
	basePath: "/",
	port: 80 as Port,
	exposeIndex: true,
	exposeHidden: true,
	denylist: [
		// linux / unix
		"/boot",
		"/dev",
		"/etc",
		"/etc/shadow",
		"/etc/gshadow",
		"/etc/passwd",
		"/etc/group",
		"/etc/sudoers",
		"/etc/ssh",
		"/etc/ssl",
		"/etc/hostname",
		"/etc/hosts",
		"/proc",
		"/sys",
		"/lib",
		"/lib128",
		"/lib64",
		"/lib32",
		"/lib16",
		"/usr",
		"/bin",
		"/bin.usr-is-merged",
		"/sbin",
		"/sbin.usr-is-merged",
		"/run",
		"/opt",
		"/tmp",
		"/var/lib",
		"/var/log",
		"/var/run",
		"/var/cache",
		"/var/tmp",
		"/srv",
		"/root",
		// macos
		"/Applications",
		"/Library",
		"/Network",
		"/System",
		"/private",
		"/cores",
		"/.DS_Store",
		"/*/.DS_Store",
		"/.Trashes",
		"/*/.Trashes",
		// freebsd
		"/compat",
		"/rescue",
		"/var/db",
		// windows
		"/System Volume Information",
		"/$RECYCLE.BIN",
		"/hiberfil.sys",
		"/pagefile.sys",
		"/swapfile.sys",
		"/Windows",
		"/Program Files",
		"/Program Files (x86)",
		"/ProgramData",
		"/Users/*/AppData",
		"/Users/*/NTUSER.DAT",
		"PerfLogs",
		"Recovery",
		"Config.Msi",
		"MSOCache",
		"Documents and Settings",
		// other
		"/system",
		"/lost+found",
		"/*/lost+found",
		"/snap",
		"/vmlinuz",
		"/initrd.img",
		"/cdrom",
		"/swap.img",
		"/*/swap.img",
		"/home/*/snap",
		"/home/*/syslogs",
		"/.Trash-1000",
		"/*/.Trash-1000",
		// sensitive files
		"*/id_rsa",
		"*/id_dsa",
		"*/id_ecdsa",
		"*/id_ed25519",
		"*/known_hosts",
		"*/authorized_keys",
		"*/.env",
		"*/.git",
		"/home/*/.ssh",
		"/home/*/.config",
		"/home/*/.cache",
		"/home/*/.local",
		"/home/*/.gnupg",
		// docker
		"*/Dockerfile",
		"*/docker-compose.yml",
		"*/docker-compose.yaml",
		"*/.dockerenv",
		"/run/secrets",
		"/var/run/secrets",
		"/var/lib/docker",
		"/var/lib/kubelet"
	] as string[],
	allowlist: null
} as Config
